<!DOCTYPE html>
<html lang="ja">
  <%- include("./partials/head.ejs") %>
  <body>
    <form class="login-form">
      <h2>Log in</h2>
      <label for="email" class="login-label">Email</label>
      <input type="text" name="email" required class="login-input" />
      <div class="email error"></div>
      <label for="password" class="login-label">Password</label>
      <input type="password" name="password" required class="login-input" />
      <div class="password error"></div>
      <button class="login-button">Log in</button>
    </form>

    <script>
      const form = document.querySelector(".login-form");
      const emailError = document.querySelector(".email.error");
      const passwordError = document.querySelector(".password.error");

      form.addEventListener("submit", async (e) => {
        e.preventDefault();
        //reset error message
        emailError.textContent = "";
        passwordError.textContent = "";
        //get the value
        const email = form.email.value;
        const password = form.password.value;
        //bacause input names are  linked to email and password
        try {
          const res = await fetch("/login", {
            method: "POST",
            body: JSON.stringify({ email, password }),
            headers: { "Content-Type": "application/json" },
          });
          //↓
          //server functions (authController.js)
          //↓
          console.log("when did it invoke ?");
          res.json().then((result) => {
            console.log(result);
            if (result) {
              emailError.textContent = result.email;
              passwordError.textContent = result.password;
              //ここにエラーメッセージが入るように処理を書く
            }
            if (result.user) {
              location.assign("/");
            }
          });
          //promiseResult can be got with method chain
        } catch (error) {
          console.log(error);
        }
      });
    </script>

    <%- include("./partials/footer.ejs") %>
  </body>
</html>
